# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rmessage.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"3\n\x07Message\x12\x13\n\x04head\x18\x01 \x01(\x0b\x32\x05.Head\x12\x13\n\x04\x62ody\x18\x02 \x01(\x0b\x32\x05.Body\"\x83\x01\n\x04Head\x12\x0f\n\x07version\x18\x01 \x01(\r\x12\x12\n\nrandom_num\x18\x02 \x01(\r\x12\x0f\n\x07\x66low_no\x18\x03 \x01(\r\x12\"\n\x0cmessage_type\x18\x04 \x01(\x0e\x32\x0c.MessageType\x12\x0f\n\x07request\x18\x05 \x01(\x08\x12\x10\n\x08\x61uth_key\x18\x06 \x01(\t\"\x84\x01\n\x04\x42ody\x12\x35\n\x15status_report_request\x18\x01 \x01(\x0b\x32\x14.StatusReportRequestH\x00\x12\x37\n\x16status_report_response\x18\x02 \x01(\x0b\x32\x15.StatusReportResponseH\x00\x42\x0c\n\nbody_oneof\"@\n\x0cResponseCode\x12\x19\n\x07retcode\x18\x01 \x01(\x0e\x32\x08.Retcode\x12\x15\n\rerror_message\x18\x02 \x01(\t\"\xbe\x01\n\x13StatusReportRequest\x12\x30\n\x0c\x63\x61pture_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\ncpu_number\x18\x02 \x01(\r\x12\x12\n\nmemory_cap\x18\x03 \x01(\r\x12\x0c\n\x04load\x18\x04 \x01(\x01\x12\x11\n\tcpu_usage\x18\x05 \x01(\r\x12\x14\n\x0cmemory_usage\x18\x06 \x01(\r\x12\x16\n\x0eprocess_number\x18\x07 \x01(\r\"h\n\x14StatusReportResponse\x12/\n\x0bhandle_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1f\n\x08response\x18\x02 \x01(\x0b\x32\r.ResponseCode*q\n\x0bMessageType\x12\x17\n\x13UNUSED_MESSAGE_TYPE\x10\x00\x12\x08\n\x04PING\x10\x01\x12\x08\n\x04PONG\x10\x02\x12\x19\n\x15STATUS_REPORT_REQUEST\x10\x03\x12\x1a\n\x16STATUS_REPORT_RESPONSE\x10\x04*\\\n\x07Retcode\x12\x0b\n\x07SUCCESS\x10\x00\x12\x11\n\x04\x46\x41IL\x10\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x17\n\nNOT_MASTER\x10\x9c\xff\xff\xff\xff\xff\xff\xff\xff\x01\x12\x18\n\x0bINVALID_KEY\x10\x9b\xff\xff\xff\xff\xff\xff\xff\xff\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='MessageType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNUSED_MESSAGE_TYPE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PONG', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_REPORT_REQUEST', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STATUS_REPORT_RESPONSE', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=737,
  serialized_end=850,
)
_sym_db.RegisterEnumDescriptor(_MESSAGETYPE)

MessageType = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPE)
_RETCODE = _descriptor.EnumDescriptor(
  name='Retcode',
  full_name='Retcode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAIL', index=1, number=-1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOT_MASTER', index=2, number=-100,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INVALID_KEY', index=3, number=-101,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=852,
  serialized_end=944,
)
_sym_db.RegisterEnumDescriptor(_RETCODE)

Retcode = enum_type_wrapper.EnumTypeWrapper(_RETCODE)
UNUSED_MESSAGE_TYPE = 0
PING = 1
PONG = 2
STATUS_REPORT_REQUEST = 3
STATUS_REPORT_RESPONSE = 4
SUCCESS = 0
FAIL = -1
NOT_MASTER = -100
INVALID_KEY = -101



_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='head', full_name='Message.head', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='body', full_name='Message.body', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=101,
)


_HEAD = _descriptor.Descriptor(
  name='Head',
  full_name='Head',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='Head.version', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='random_num', full_name='Head.random_num', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='flow_no', full_name='Head.flow_no', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message_type', full_name='Head.message_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request', full_name='Head.request', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auth_key', full_name='Head.auth_key', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=235,
)


_BODY = _descriptor.Descriptor(
  name='Body',
  full_name='Body',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status_report_request', full_name='Body.status_report_request', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status_report_response', full_name='Body.status_report_response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='body_oneof', full_name='Body.body_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=238,
  serialized_end=370,
)


_RESPONSECODE = _descriptor.Descriptor(
  name='ResponseCode',
  full_name='ResponseCode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='retcode', full_name='ResponseCode.retcode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='ResponseCode.error_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=436,
)


_STATUSREPORTREQUEST = _descriptor.Descriptor(
  name='StatusReportRequest',
  full_name='StatusReportRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='capture_time', full_name='StatusReportRequest.capture_time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpu_number', full_name='StatusReportRequest.cpu_number', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memory_cap', full_name='StatusReportRequest.memory_cap', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='load', full_name='StatusReportRequest.load', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpu_usage', full_name='StatusReportRequest.cpu_usage', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memory_usage', full_name='StatusReportRequest.memory_usage', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='process_number', full_name='StatusReportRequest.process_number', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=439,
  serialized_end=629,
)


_STATUSREPORTRESPONSE = _descriptor.Descriptor(
  name='StatusReportResponse',
  full_name='StatusReportResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='handle_time', full_name='StatusReportResponse.handle_time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='response', full_name='StatusReportResponse.response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=631,
  serialized_end=735,
)

_MESSAGE.fields_by_name['head'].message_type = _HEAD
_MESSAGE.fields_by_name['body'].message_type = _BODY
_HEAD.fields_by_name['message_type'].enum_type = _MESSAGETYPE
_BODY.fields_by_name['status_report_request'].message_type = _STATUSREPORTREQUEST
_BODY.fields_by_name['status_report_response'].message_type = _STATUSREPORTRESPONSE
_BODY.oneofs_by_name['body_oneof'].fields.append(
  _BODY.fields_by_name['status_report_request'])
_BODY.fields_by_name['status_report_request'].containing_oneof = _BODY.oneofs_by_name['body_oneof']
_BODY.oneofs_by_name['body_oneof'].fields.append(
  _BODY.fields_by_name['status_report_response'])
_BODY.fields_by_name['status_report_response'].containing_oneof = _BODY.oneofs_by_name['body_oneof']
_RESPONSECODE.fields_by_name['retcode'].enum_type = _RETCODE
_STATUSREPORTREQUEST.fields_by_name['capture_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_STATUSREPORTRESPONSE.fields_by_name['handle_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_STATUSREPORTRESPONSE.fields_by_name['response'].message_type = _RESPONSECODE
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['Head'] = _HEAD
DESCRIPTOR.message_types_by_name['Body'] = _BODY
DESCRIPTOR.message_types_by_name['ResponseCode'] = _RESPONSECODE
DESCRIPTOR.message_types_by_name['StatusReportRequest'] = _STATUSREPORTREQUEST
DESCRIPTOR.message_types_by_name['StatusReportResponse'] = _STATUSREPORTRESPONSE
DESCRIPTOR.enum_types_by_name['MessageType'] = _MESSAGETYPE
DESCRIPTOR.enum_types_by_name['Retcode'] = _RETCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  ))
_sym_db.RegisterMessage(Message)

Head = _reflection.GeneratedProtocolMessageType('Head', (_message.Message,), dict(
  DESCRIPTOR = _HEAD,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:Head)
  ))
_sym_db.RegisterMessage(Head)

Body = _reflection.GeneratedProtocolMessageType('Body', (_message.Message,), dict(
  DESCRIPTOR = _BODY,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:Body)
  ))
_sym_db.RegisterMessage(Body)

ResponseCode = _reflection.GeneratedProtocolMessageType('ResponseCode', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSECODE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:ResponseCode)
  ))
_sym_db.RegisterMessage(ResponseCode)

StatusReportRequest = _reflection.GeneratedProtocolMessageType('StatusReportRequest', (_message.Message,), dict(
  DESCRIPTOR = _STATUSREPORTREQUEST,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:StatusReportRequest)
  ))
_sym_db.RegisterMessage(StatusReportRequest)

StatusReportResponse = _reflection.GeneratedProtocolMessageType('StatusReportResponse', (_message.Message,), dict(
  DESCRIPTOR = _STATUSREPORTRESPONSE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:StatusReportResponse)
  ))
_sym_db.RegisterMessage(StatusReportResponse)


# @@protoc_insertion_point(module_scope)
